<?php
declare(strict_types = 1);
/**
 * @file
 * Procedural code for image_auto_tag module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\image_auto_tag\AzureCognitiveServices;
use Drupal\image_auto_tag\Entity\PersonMap;
use Drupal\image_auto_tag\ImageAutoTagInterface;
use GuzzleHttp\Exception\TransferException;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add a setting for face detection on image fields.
 */
function image_auto_tag_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\field\FieldConfigInterface $entity */
  $entity = $form_state->getFormObject()->getEntity();
  if ($entity->getFieldStorageDefinition()->getType() === 'image') {
    $form['third_party_settings']['image_auto_tag']['detect_faces'] = [
      '#type' => 'checkbox',
      '#title' => t('Detect faces in uploaded images'),
      '#description' => t('Submit images for face detection using Image Auto Tag module.'),
      '#default_value' => $entity->getThirdPartySetting('image_auto_tag', 'detect_faces'),
    ];
    // If the module isn't configured yet.
    if (\Drupal::config('image_auto_tag.settings')->get('person_entity_bundle') === NULL) {
      $form['third_party_settings']['image_auto_tag']['detect_faces'] = [
        '#description' => t('Submit images for face detection using Image Auto Tag module.  You must configure the module before you can use it!'),
        '#disabled' => TRUE,
      ] + $form['third_party_settings']['image_auto_tag']['detect_faces'];
      return;
    }
    // Build a list of entity reference fields pointing to the right type.
    $tagFieldOptions = [];
    // Look up "the right type" in config.
    $targetEntityBundleString = \Drupal::config('image_auto_tag.settings')->get('person_entity_bundle');
    list($targetEntityType, $targetEntityBundle) = explode('.', $targetEntityBundleString);
    $fieldInstances = \Drupal::service('entity_field.manager')->getFieldDefinitions($entity->getTargetEntityTypeId(), $entity->getTargetBundle());
    foreach ($fieldInstances as $fieldName => $fieldInstance) {
      // If it's an entity reference pointing at the right type.
      if ($fieldInstance->getType() === 'entity_reference' && $fieldInstance->getSettings()['target_type'] === $targetEntityType) {
        $tagFieldOptions[$fieldName] = $fieldName;
      }
    }
    if ($tagFieldOptions === []) {
      $form['third_party_settings']['image_auto_tag']['detect_faces'] = [
        '#description' => t('Submit images for face detection using Image Auto Tag module.  No entity reference field found on this bundle, which references the "people" type defined in settings. Please check your settings for image_auto_tag and try again.'),
        '#disabled' => TRUE,
      ] + $form['third_party_settings']['image_auto_tag']['detect_faces'];
    }
    else {
      $form['third_party_settings']['image_auto_tag']['tag_field'] = [
        '#title' => t('Tag field'),
        '#description' => t('The field which will receive tags based on face recognition. Manual entries into this field will be overwritten when detection is performed!'),
        '#type' => 'select',
        '#options' => $tagFieldOptions,
        '#default_value' => $entity->getThirdPartySetting('image_auto_tag', 'tag_field'),
        '#states' => [
          'visible' => [
            ':input[name="third_party_settings[image_auto_tag][detect_faces]"]' => ['checked' => TRUE],
          ],
        ],
      ];
    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function image_auto_tag_entity_presave(EntityInterface $entity) {
  if (!($entity instanceof ContentEntityInterface) || $entity instanceof PersonMap) {
    return;
  }
  // If the entity has a field that should have face detection performed, submit
  // images and tag.
  foreach ($entity->getFieldDefinitions() as $fieldDefinition) {
    $fieldName = $fieldDefinition->getName();
    // If this in an image field, with 'detect_faces'=TRUE, and this is either
    // a new entity, or an updated field value.
    if ($fieldDefinition->getType() === 'image' &&
      $fieldDefinition->getThirdPartySetting('image_auto_tag', 'detect_faces') &&
      (!isset($entity->original) || $entity->get($fieldName)->entity->id() !== $entity->original->get($fieldName)->entity->id())
    ) {
      // If this should be processed asynchronously, queue it and return.
      if (\Drupal::config('image_auto_tag.settings')->get('synchronous_mode') === FALSE) {
        // Queue processing for later.
        /** @var \Drupal\Core\Queue\QueueFactory $queue_factory */
        $queue_factory = \Drupal::service('queue');
        /** @var \Drupal\Core\Queue\QueueInterface $queue */
        $queue = $queue_factory->get('image_auto_tag_detect_faces');
        $item = [
          'entityId' => $entity->id(),
          'entityType' => $entity->getEntityTypeId(),
          'fieldName' => $fieldName,
        ];
        $queue->createItem($item);
        return;
      }
      /** @var \Drupal\image_auto_tag\EntityOperations $imageAutoTagOperations */
      $imageAutoTagOperations = \Drupal::service('image_auto_tag.entity_operations');
      $imageAutoTagOperations->findFacesAndTag($entity, $fieldDefinition);
      // Set a message.
      $count = $entity->{$fieldName}->count();
      \Drupal::messenger()->addStatus("Detected {$count} faces.");
    }
  }
}

/**
 * Implements hook_entity_insert().
 */
function image_auto_tag_entity_insert(EntityInterface $entity) {
  _image_auto_tag_entity_post_save($entity);
}

/**
 * Implements hook_entity_update().
 */
function image_auto_tag_entity_update(EntityInterface $entity) {
  _image_auto_tag_entity_post_save($entity);
}

/**
 * Entity insert and update hook.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The entity that has just been saved.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 * @throws \Drupal\Core\TypedData\Exception\MissingDataException
 * @throws \GuzzleHttp\Exception\GuzzleException
 */
function _image_auto_tag_entity_post_save(EntityInterface $entity) {
  if (!($entity instanceof ContentEntityInterface)) {
    return;
  }
  $config = \Drupal::config('image_auto_tag.settings');
  // Check entity type and bundle.
  $targetEntityBundleString = $config->get('person_entity_bundle');
  list($targetEntityType, $targetEntityBundle) = explode('.', $targetEntityBundleString);
  // If the entity is our "people" entity, check faces.
  if ($entity->getEntityTypeId() === $targetEntityType && $entity->bundle() === $targetEntityBundle) {
    // If this should be processed asynchronously, queue it and return.
    if ($config->get('synchronous_mode') === FALSE) {
      // Queue processing for later.
      /** @var \Drupal\Core\Queue\QueueFactory $queue_factory */
      $queue_factory = \Drupal::service('queue');
      /** @var \Drupal\Core\Queue\QueueInterface $queue */
      $queue = $queue_factory->get('image_auto_tag_process_person');
      $item = [
        'entityId' => $entity->id(),
        'entityType' => $entity->getEntityTypeId(),
      ];
      $queue->createItem($item);
      return;
    }
    /** @var \Drupal\image_auto_tag\EntityOperations $entityOperations */
    $entityOperations = \Drupal::service('image_auto_tag.entity_operations');
    try {
      $entityOperations->syncPerson($entity);
    }
    catch (TransferException $e) {
      \Drupal::messenger()->addWarning(t('Unable to submit face images to Azure for processing. Error: %code : %msg.',
        [
          '%code' => $e->getCode(),
          '%msg' => $e->getMessage(),
        ]
      ));
    }
  }
}

/**
 * Implements hook_entity_delete().
 *
 * Clean up when a mapped entity is deleted.
 */
function image_auto_tag_entity_delete(EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    // If this should be processed asynchronously, queue it and return.
    if (\Drupal::config('image_auto_tag.settings')->get('synchronous_mode') === FALSE) {
      // Queue processing for later.
      /** @var \Drupal\Core\Queue\QueueFactory $queue_factory */
      $queue_factory = \Drupal::service('queue');
      /** @var \Drupal\Core\Queue\QueueInterface $queue */
      $queue = $queue_factory->get('image_auto_tag_deleted_entity');
      $item = [
        'entityId' => $entity->id(),
        'entityType' => $entity->getEntityTypeId(),
      ];
      $queue->createItem($item);
      return;
    }
    $personMapResult = \Drupal::entityQuery('image_auto_tag_person_map')
      ->condition('local_id', $entity->id())
      ->condition('local_entity_type', $entity->getEntityTypeId())
      ->execute();
    if ($personMapResult > 0) {
      /** @var \Drupal\image_auto_tag\Entity\PersonMap $personMaps */
      $personMaps = PersonMap::loadMultiple($personMapResult);
      foreach ($personMaps as $personMap) {
        // @todo: implement this.
        $personMap->delete();
      }
    }
  }
}
