<?php
declare(strict_types = 1);
/**
* @file
* Procedural code for media_auto_tag module.
*/

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\media_auto_tag\AzureCognitiveServices;
use Drupal\media_auto_tag\Entity\PersonMap;
use GuzzleHttp\Exception\TransferException;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add a setting for face detection on image fields.
 */
function media_auto_tag_form_field_config_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\field\FieldConfigInterface $entity */
  $entity = $form_state->getFormObject()->getEntity();
  if ($entity->getFieldStorageDefinition()->getType() === 'image') {
    $form['third_party_settings']['media_auto_tag']['detect_faces'] = [
      '#type' => 'checkbox',
      '#title' => t('Detect faces in uploaded images'),
      '#description' => t('Submit images for face detection using Media Auto Tag module.'),
      '#default_value' => $entity->getThirdPartySetting('media_auto_tag', 'detect_faces'),
    ];
    // If the module isn't configured yet.
    if (\Drupal::config('media_auto_tag.settings')->get('person_entity_bundle') === NULL) {
      $form['third_party_settings']['media_auto_tag']['detect_faces'] = [
        '#description' => t('Submit images for face detection using Media Auto Tag module.  You must configure the module before you can use it!'),
        '#disabled' => TRUE,
      ] + $form['third_party_settings']['media_auto_tag']['detect_faces'];
      return;
    }
    // Build a list of entity reference fields pointing to the right type.
    $tagFieldOptions = [];
    // Look up "the right type" in config.
    $targetEntityBundleString = \Drupal::config('media_auto_tag.settings')->get('person_entity_bundle');
    list($targetEntityType, $targetEntityBundle) = explode('.', $targetEntityBundleString);
    $fieldInstances = \Drupal::service('entity_field.manager')->getFieldDefinitions($entity->getTargetEntityTypeId(), $entity->getTargetBundle());
    foreach ($fieldInstances as $fieldName => $fieldInstance) {
      // If it's an entity reference pointing at the right type.
      if ($fieldInstance->getType() === 'entity_reference' && $fieldInstance->getSettings()['target_type'] === $targetEntityType) {
        $tagFieldOptions[$fieldName] = $fieldName;
      }
    }
    if ($tagFieldOptions === []) {
      $form['third_party_settings']['media_auto_tag']['detect_faces'] = [
        '#description' => t('Submit images for face detection using Media Auto Tag module.  No entity reference field found on this bundle, which references the "people" type defined in settings. Please check your settings for media_auto_tag and try again.'),
        '#disabled' => TRUE,
      ] + $form['third_party_settings']['media_auto_tag']['detect_faces'];
    }
    else {
      $form['third_party_settings']['media_auto_tag']['tag_field'] = [
        '#title' => t('Tag field'),
        '#description' => t('The field which will receive tags based on face recognition. Manual entries into this field will be overwritten when detection is performed!'),
        '#type' => 'select',
        '#options' => $tagFieldOptions,
        '#default_value' => $entity->getThirdPartySetting('media_auto_tag', 'tag_field'),
        '#states' => [
          'visible' => [
            ':input[name="third_party_settings[media_auto_tag][detect_faces]"]' => ['checked' => TRUE],
          ],
        ],
      ];
    }
  }
}

/**
 * Implements hook_entity_insert().
 */
function media_auto_tag_entity_insert(EntityInterface $entity) {
  if (!($entity instanceof ContentEntityInterface)) {
    return;
  }
  // If the entity is our "people" entity, submit faces and initiate training.
  $config = \Drupal::config('media_auto_tag.settings');
  // Check entity type and bundle.
  $targetEntityBundleString = $config->get('person_entity_bundle');
  list($targetEntityType, $targetEntityBundle) = explode('.', $targetEntityBundleString);
  if ($entity->getEntityTypeId() === $targetEntityType && $entity->bundle() === $targetEntityBundle) {
    /** @var \Drupal\media_auto_tag\AzureCognitiveServices $azure */
    $azure = \Drupal::service('media_auto_tag.azure');
    // Check availability of the service.
    if ($azure->serviceStatus()) {
      // Create the Person record.
      $person = $azure->createPerson(AzureCognitiveServices::PEOPLE_GROUP, $entity->label());
      $personId = $person->personId;
      // Create the personMap record.
      PersonMap::create([
        'foreign_id' => $personId,
        'local_id' => $entity->id(),
        'local_entity_type' => $entity->getEntityTypeId(),
      ])->save();
      // Submit each value on the image field as a "face".
      $targetImageField = explode('.', $config->get('person_image_field'))[1];
      foreach ($entity->get($targetImageField)->getValue() as $index => $value) {
        /** @var \Drupal\Core\Image\Image $image */
        $image = $entity->get($targetImageField)->get($index);
        $imagePath = $image->entity->getFileUri();
        try {
          $faceId = $azure->addFace(AzureCognitiveServices::PEOPLE_GROUP, $personId, $imagePath);
          PersonMap::create([
            'foreign_id' => $faceId->persistedFaceId,
            'local_id' => $image->entity->id(),
            'local_entity_type' => 'file',
          ])->save();
        }
        catch (TransferException $e) {
          \Drupal::messenger()->addWarning(t('Unable to submit face images to Azure for processing. Error: %code : %msg.',
            [
              '%code' => $e->getCode(),
              '%msg' => $e->getMessage(),
            ]
          ));
        }
      }
    }
  }
  // If the entity has a field that should have face detection performed, submit images and tag.
  foreach ($entity->getFieldDefinitions() as $fieldDefinition) {
    if ($fieldDefinition->getType() === 'image' && $fieldDefinition->getThirdPartySetting('media_auto_tag', 'detect_faces')) {
      /** @var \Drupal\media_auto_tag\AzureCognitiveServices $azure */
      $azure = \Drupal::service('media_auto_tag.azure');
      // Check availability of the service.
      if ($azure->serviceStatus()) {
        $fileUri = $entity->{$fieldDefinition->getName()}->entity->getFileUri();
        $detectedFaces = $azure->detectFaces($fileUri);
        if (!empty($detectedFaces)) {
          // Identify detected faces.
          $facesToIdentify = [];
          foreach ($detectedFaces as $detectedFace) {
            $facesToIdentify[] = $detectedFace->faceId;
          }
          $identifiedFaces = $azure->identifyFaces(array_slice($detectedFaces, 0, 10), AzureCognitiveServices::PEOPLE_GROUP);
          // Loop over the identified faces and tag with their Drupal entities.
          $personIds = [];
          foreach ($identifiedFaces as $identifiedFace) {
            // Take the first candidate.
            $personIds[] = $identifiedFace->candidates[0]->personId;
          }
          $personMapResult = \Drupal::entityQuery('media_auto_tag_person_map')
            ->condition('foreign_id', $personIds, 'IN')
            ->execute();
          $personMaps = PersonMap::loadMultiple($personMapResult);
          // Apply this as the target field value.
          $targetTagField = $fieldDefinition->getThirdPartySetting('media_auto_tag', 'tag_field');
          $entity->set($targetTagField, $personMaps);
          $entity->save();
        }
      }
    }
  }
}


/**
 * Implements hook_entity_update().
 */
function media_auto_tag_entity_update(EntityInterface $entity) {
}
