# Schema for the configuration files of the image_auto_tag module.

image_auto_tag.settings:
  type: config_object
  label: 'Image Auto Tag settings'
  mapping:
    azure_endpoint:
      type: string
      label: 'Azure endpoint URL'
    azure_service_key:
      type: string
      label: 'Azure service key'
    person_entity_bundle:
      type: string
      label: 'Person entity bundle'
    person_image_field:
      type: string
      label: 'Person image field'
    synchronous:
      type: boolean
      label: 'Synchronous mode'
field.field.*.*.*.third_party.image_auto_tag:
  type: mapping
  label: 'Image Auto Tag'
  mapping:
    detect_faces:
      type: boolean
      label: 'Whether to enable face detection/recognition on this field'
    tag_field:
      type: string
      label: 'field to tag'